id: IFF0AFE57
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T08:24:13+00:00'
last_modified: '2022-06-15T18:27:38.297016+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN6721
  title: སློབ་གཞི་འགྲེལ་བརྗོད་ངོ་མཚར་འཕྲུལ་གྱི་ལྡེ་མིག ༼ལོ་རིམ་དྲུག་པའི་དེབ་སྟོད་ཆ།༽
  author: ''
  access: http://purl.bdrc.io/admindata/AccessRestrictedTemporarily
  restrictedInChina: false
  base:
    '5803':
      image_group_id: I3CN6723
      title: Volume 1 of slob gzhi 'grel brjod ngo mtshar 'phrul gyi lde mig(lo rim
        drug pa'i deb stod cha/)
      total_pages: 260
      order: 1
      base_file: 5803.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
